apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: db-secret
  namespace: aoc-web
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAXyFuelK4BaGk/2MU0GIlDnNVoSq+1kBhNk2EXraX08gcFNcA/w69qrBjP9G5JtVMyZ2Fi5v2fU7ZjDhDEqBtVa0M8o1YhocX1GQkzu7gKLX6N72jvAdrJP9QOTHbx3F9bGTZ7N1MOU/IqebCd1a/H+U1a7ctmMt86K1iGiXkgQ3BmWi/gz63asNj/SSzpLfw2AZxIWKxEC40JZmh9FniN3OsU/DZV21o8BOtbydLrX76KOkTFZDAZ4SyC2beNofsvvYQj4GeZgWp7YoTxptYhwoiGS8r9jc7pMVt54p0Dzo6XameNVptZdT+JcawPjS9gTTOZvdU1S/3wN6Dozr0oRhaGewWUftJH53poDidnsM7iGBR7DvSkczJNd6/ZGkxBwtLAiUp0fEa5hLqj8rl6uozWgPLvSlaC4CwJq73Awno8NdpMXASLn9194oMg95kJJ9spXSP09GTXYSvTlSU32FjzHyPkdqPDo7Tktbzv2NzfFYe1ZeQjgzEWhzmaBRLK2JExwh1uX1fVtLV0xfIB20YTl8tB/5umAii6C7+VBnVFf/+mIsnM2ZF7BNf/yQ5M/mjIm9cQC4ab16uppvzKSVV3b0ZioO+4F7pz4bmsJi2csIv1Dp65hW0XjAsLwfoU8kukKuR/6FiuuIsyjKavPrfousDCypqoOSxs5NMe9exY5TW6dptrgHogU6n0LwmQTCv6wf9WIrL7KmixOg3gLbH3CF3RHiw=
    POSTGRES_POSTGRES_PASSWORD: AgCWXEWdmBHeq1pVDUmBzcQ+fJfgxVbAeUFvOdcnDtQnWtF4OsUedH2G3G/XPkZmFcHX4Ul7UZCDdVlt+gPayzwX9eVlkhdWKOgGDS+53PHK47PD9VPizEZ6b7zem1C7FWA5m2/E+s6GhDhntoiiNuYIuaKYNfVJkNe1B6ILEU0mUbNovSGToxGOEQnPz+CZRySSXLXLv0t9tEnS55QFzXX24KvI0iVkVOrUvpTnayZ8eqrbv05N33JrGdIhz9+iEbIovEmid+JBblaJdNahFTN/KkLjVKmbllwkDBmtSrvxyyami1N3RoHd705gB0CJj5ybkhYDehDZbTypTAeXi0yr0BIiCTl1Vt3a9jHUhkUlI9aiMvMdGPIsyVHnrUR7e7OwJ89P2WrTOFb/8V6ZNXUY03k5MZqpQMotxw+JPXMomzPec1fOSJbuBNchmjSyVy4A42VJyOoik0c0Fn2cKdddTDjGu4rJR9PNjDcEy+VK5eG5PkX/R/WBICbrdM+LT8qVfwkYIzR9P5qxmRLL15XK8xCkyptIJhjoyb8wgBtsEsAnQsxMb0B7K1Hk2W6Ks3ZA/XmBj+lWCBnSHdf/zVVYQZdUV4o/ZZIFzz/nmzobC5swr/bC9aUQvwE8zYwPoxLYH/H+Zjpmu5ZCLKv7Zz3/Qn33spWuaME1jHcjgn/q2yc+y7bZLqU7hBDnjM4vCnMuFpZ+t8Mr4nGDVop6tg4zPeQPX2VsjEs=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: db-secret
      namespace: aoc-web
    type: Opaque

