---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
  - ../../components/db
  - aoc-sealed-secret.yaml
  - db-secret.yaml
namespace: "aoc-web"
namePrefix: "aoc-web-"
images:
  - name: "mattcl/aoc-web"
    newTag: "0.2.2"
  - name: "mattcl/aoc-ui"
    newTag: "0.13.6"
  - name: "docker.io/bitnami/postgresql"
    newTag: "15.3.0-debian-11-r9"

replicas:
  - name: app
    count: 2
  - name: frontend
    count: 2

configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"
  # we're going to trigger the rollout by additionally having a generated
  # config map that changes when the sealed secret is updated.
  # See: https://github.com/kubernetes-sigs/kustomize/issues/702
  - name: db-sentinel
    files:
      - db-secret.yaml
  - name: aoc-sentinel
    files:
      - aoc-sealed-secret.yaml
  # for configuring the db statefulset
  - name: db-config
    envs:
      - db-config.env
  # for configuring app(s) to talk to the db
  - name: db-connect
    envs:
      - db-connect.env
