---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: app
          image: "mattcl/aoc-web:latest"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "app-config"
            - configMapRef:
                name: "aoc-sentinel"
            - configMapRef:
                name: "db-sentinel"
            - configMapRef:
                name: "db-connect"
            - secretRef:
                # we can't let kustomize handle this because this secret is
                # unknown to it because it's the result of unsealing the secret
                name: "aoc-web-db-secret"
            - secretRef:
                # we can't let kustomize handle this because this secret is
                # unknown to it because it's the result of unsealing the secret
                name: "aoc-web-aoc-secret"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 2
            terminationGracePeriodSeconds: 5
